Add files via upload
I hate windows... look what I get every time I try to commit something to the project:

C:\Users\pietr\PycharmProjects\Bellman-Ford>git push origin master
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
      7 [main] cat (12984) D:\cygwin64\bin\cat.exe: *** fatal error - cygheap base mismatch detected - 0x1802F7408/0x1802F3408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
error: failed to execute prompt script (exit code 127)
fatal: could not read Username for 'https://github.com': No error

So, I decided to do a power point.